services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

    env_file:
      - .env

    volumes:
      - ./data:/app/data  # Ma'lumotlarni saqlash uchun jild
    restart: unless-stopped  # Konteyner o'chganda avto-qayta ishga tushadi

volumes:
  data:  # Ma'lumotlarni saqlash uchun nomlangan jild